/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author omar-abdelrahman
 */

#include <bits/stdc++.h>

template<typename U, typename V>
std::istream& operator >> (std::istream& in, std::pair<U, V>& p) {
  return in >> p.first >> p.second;
}

template<typename U, typename V>
std::ostream& operator << (std::ostream& out, const std::pair<U, V>& p) {
  return out << p.first << ' ' << p.second;
}

template<typename T>
std::istream& operator >> (std::istream& in, std::vector<T>& v) {
  for (auto& vi : v) in >> vi;
  return in;
}

template<typename T>
std::ostream& operator << (std::ostream& out, const std::vector<T>& v) {
  const int n = static_cast<int>(v.size());
  for (int i = 0; i < n; i++) {
    if (i > 0) out << ' ';
    out << v[i];
  }
  return out;
}

template<typename T_vector>
void print_vector_h(std::ostream& out, const T_vector& v, const bool& new_line = false) {
  const int n = static_cast<int>(v.size());
  for (int i = 0; i < n; i++) {
    if (i > 0) out << ' ';
    out << v[i];
  }
  if (new_line) out << '\n';
}

template<typename T_vector>
void print_vector_v(std::ostream& out, const T_vector& v, const bool& new_line = false) {
  const int n = static_cast<int>(v.size());
  for (int i = 0; i < n; i++) {
    out << v[i] << '\n';
  }
  if (new_line) out << '\n';
}

template<typename U, typename V>
void print_pretty_pair(std::ostream& out, const std::pair<U, V>& p, const bool& new_line = false) {
  out << '{' << p.first << ", " << p.second << '}';
  if (new_line) out << '\n';
}

#define _size(a) (int) (a).size()

using namespace std;

class BMilenaAndAdmirer {
public:
  void solveOne() {
    int n;
    in >> n;
    vector<int64_t> a(n);
    in >> a;
    int64_t result = 0;
    for (int i = n - 2; i >= 0; i--) {
      if (a[i] <= a[i + 1]) {
        continue;
      }
      if (a[i] % a[i + 1] == 0) {
        result += a[i] / a[i + 1] - 1;
        a[i] = a[i + 1];
      } else {
        int64_t k = a[i] / a[i + 1] + 1;
        result += k - 1;
        a[i] /= k;
      }
    }
    out << result << '\n';
  }

  void solve() {
    int nt;
    in >> nt;
    for (int _ = 0; _ < nt; _++) {
      solveOne();
    }
  }

  BMilenaAndAdmirer(istream& in, ostream& out)
    : in(in), out(out) { }

private:
  ostream& out;
  istream& in;
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);
  BMilenaAndAdmirer solver(cin, cout);
  solver.solve();
  return 0;
}
